### ISSUE TITLE
Workspace Resolver Warning

### ISSUE THREAD

**Issue by bh2smith** [nlordell/ethcrates-rs#5]
When running cargo check we are getting these resolver warnings. Not sure which option you want to go with or I would fix it:

```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```

**Comment by nlordell** [comment]
No need to create an issue for something so small, where the PR can include this description - but thanks for being extra pedantic with this :)

**Comment by bh2smith** [comment]
I had not planned on actually doing the PR because I wasn't sure, then I just did it anyway.
